#!/bin/bash

filename="$HOME/.exercise"

if [ ! -f "$filename" ]; then
  touch "$filename"
fi

function usage() {
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  add <exercise> <reps> - add a new exercise"
  echo "  today <exercise> - show today's reps for an exercise"
  echo "  count <exercise> - show total reps for an exercise"
  echo "  start <exercise> <reps> <interval> - start a timer for an exercise"
  echo "  goal <start time> <end time> <exercise> <start reps> <end reps> - show progress towards a goal"
  echo "  workout <file> <sets> - start a workout"
  echo "  records - show records"
  echo "  show - show all exercises"
  echo "  edit - edit the exercise file"
  echo "  summary <date> - show summary for a date"
  echo "  graph - show graph"
  echo "  help - show this help"
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

function countdown() {
  secs=$1
  while [ "$secs" -gt 0 ]; do
    read -r -t 1 -n 1 input
    if [ $? -eq 0 ]; then
      if [ "$input" = "" ]; then
        break
      fi
    fi
    echo -ne "$secs\033[0K\r"
    : $((secs--))
  done
}

case "$1" in
  add)
    if [ $# -ne 3 ]; then
      echo "Usage: $0 add <exercise> <reps>"
      exit 1
    fi
    echo "$(date '+%Y-%m-%d %H:%M:%S')	$3	$2" >> "$filename"
    ;;
  today)
    if [ $# -ne 2 ]; then
      echo "Usage: $0 today <exercise>"
      exit 1
    fi
    date=$(date +%Y-%m-%d)
    grep "$date" "$filename" | grep "$2" | \
    awk -F '\t' '
          BEGIN {sum=0}
          {sum+=$2}
        END {print sum, "today"}'
    ;;
  count)
    if [ $# -ne 2 ]; then
      echo "Usage: $0 count <exercise>"
      exit 1
    fi

    exercise="$2"

    awk '
      BEGIN { a=0 }
      {
        if($4=="'"$exercise"'"){
          a+=$3
        }
      }
      END { print a }' < "$filename"
    ;;
  start)
    if [ $# -ne 4 ]; then
      echo "Usage: $0 start <exercise> <reps> <interval>"
      exit 1
    fi
    while true; do
      "$0" add "$2" "$3"
      echo "Added $3 $2"

      "$0" today "$2"

      countdown "$4"

      read -r -p "Continue? [y/n] " yn
      case "$yn" in
        [Yy]* ) continue;;
        [Nn]* ) break;;
        * ) continue;;
      esac
    done
    ;;
  goal)
    if [ $# -ne 6 ]; then
      echo "Usage: $0 goal <start time> <end time> <exercise> <start reps> <end reps>"
    fi

    start_time="$(date -d "$2" +%s)"
    end_time="$(date -d "$3" +%s)"
    exercise="$4"
    start_reps="$5"
    end_reps="$6"

    while :; do
      current_time="$(date +%s)"
      awk -F '\t' -v start_time="$start_time" -v end_time="$end_time" -v exercise="$exercise" -v start_reps="$start_reps" -v end_reps="$end_reps" -v current_time="$current_time" '
        END {
          estimated_progress = (current_time - start_time) / (end_time - start_time)
          estimated_reps = start_reps + (end_reps - start_reps) * estimated_progress
          print "Estimated reps for " exercise ": " estimated_reps
        }
      ' "$filename"
      "$0" today "$exercise"
      sleep 1
    done
    ;;
  workout)
    workout_file=""
    sets=0

    if [ $# -eq 3 ]; then
      workout_file="$2"
      sets="$3"
    elif [ $# -eq 2 ]; then
      workout_file="$HOME/.config/last_workout"
      $EDITOR "$workout_file"
      sets="$2"
    else
      echo "Usage:"
      echo "	$0 workout <file> <sets>"
      echo "	$0 workout <sets>"
      exit 1
    fi

    for ((i=1; i<sets+1; i++)); do
      while read -r line <&3; do
        if [ -z "$line" ]; then
          continue
        fi

        if [[ "$line" =~ ^# ]]; then
          continue
        fi

        exercise="$(echo "$line" | awk '{print $1}')"
        reps="$(echo "$line" | awk '{print $2}')"
        interval="$(echo "$line" | awk '{print $3}')"

        "$0" add "$exercise" "$reps"
        echo "Added $reps $exercise"

        "$0" today "$exercise"

        countdown "$interval"

        echo "Sets left: $((sets - i))/$sets"
        read -r -p "Continue? [y/n] " yn
        case "$yn" in
          [Yy]* ) continue;;
          [Nn]* ) exit;;
          * ) continue;;
        esac

      done 3< "$workout_file"
    done
    ;;
  show)
    (
      printf "Date\tCurls\tPushups\tPullups\tEndurance\n"
      cat "$filename" | awk -F '\t' '
      BEGIN {
      }
      {
        split($1, a, " ")
        data[a[1]][$3] += $2
      }
      END {
        for (date in data) {
          printf "%s\t", date
          printf "%d\t", data[date]["curls"]
          printf "%d\t", data[date]["pushups"]
          printf "%d\t", data[date]["pullups"]
          printf "%d\t", data[date]["endurance"]
          printf "\n"
        }
      }
      ' | sort
    ) | column -t
    ;;
  records)
    (
      echo "Reps	Exercise"
      awk '{print $4}' "$filename" | sort | uniq | while read -r line; do
        awk -F '\t' '
        BEGIN {
          OFS="\t"
          a=0
        }
        /'"$line"'/ {
          if ($2>a) {
            a=$2
          }
        }
        END {
          print a, "'"$line"'"
        }' < "$filename"
      done
    ) | column -t -s $'\t'
    ;;
  edit)
    "$EDITOR" "$filename"
    ;;
  summary)
    date=$(date +%Y-%m-%d)

    if [ $# -eq 2 ]; then
      date="$2"
    fi

    grep "$date" "$filename" | \
    awk -F '\t' '
        BEGIN {
          categories["curls"] = 0
          categories["pullups"] = 0
          categories["pushups"] = 0
          categories["endurance"] = 0
        }
        {
          categories[$3] += $2
        }
        END {
          for (category in categories) {
            print category, categories[category]
          }
        }
        '
    ;;
  graph)
    "$0" show > /tmp/fitness_data.txt
    gnuplot << EOF
set terminal svg size 1024,768 enhanced font 'Verdana,20'
set output '/tmp/fitness_graph.svg'

# Title and labels
set title "Fitness Activity Over Time"
set xlabel "Date"
set ylabel "Reps"
set grid
set xdata time
set timefmt "%Y-%m-%d"
set format x "%Y-%m-%d"
set xtics rotate by -20

plot '/tmp/fitness_data.txt' \
        using 1:2 title 'Curls' with lines linewidth 2 smooth csplines, \
     '' using 1:3 title 'Pushups' with lines linewidth 2 smooth csplines, \
     '' using 1:4 title 'Pullups' with lines linewidth 2 smooth csplines, \
     '' using 1:5 title 'Endurance' with lines linewidth 2 smooth csplines

set output
EOF
    firefox fitness_graph.svg
    ;;
  help)
    usage
    ;;
  *)
    echo "Unknown command: $1"
    exit 1
    ;;
esac
